// <auto-generated />
namespace AlfaPeople.KingKhalidFoundation.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddReminderDateToProjectImpactEvaluation1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReminderDateToProjectImpactEvaluation1));
        
        string IMigrationMetadata.Id
        {
            get { return "202602030937255_AddReminderDateToProjectImpactEvaluation1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
