// <auto-generated />
namespace AlfaPeople.KingKhaledFoundation.Admin.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddIncubationWorkshopAndQuestions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIncubationWorkshopAndQuestions));
        
        string IMigrationMetadata.Id
        {
            get { return "202411200711333_AddIncubationWorkshopAndQuestions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
