//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaPeople.KingKhaledFoundation.Admin.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CorporationProfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorporationProfile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfaPeople.KingKhaledFoundation.Admin.Web.App_GlobalResources.CorporationProfile", typeof(CorporationProfile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absent.
        /// </summary>
        public static string absent {
            get {
                return ResourceManager.GetString("absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Email.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Email.
        /// </summary>
        public static string AdministratorEmail {
            get {
                return ResourceManager.GetString("AdministratorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for requesting modification.
        /// </summary>
        public static string AskForUpdate {
            get {
                return ResourceManager.GetString("AskForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Certificate of Registration Corporate.
        /// </summary>
        public static string AttachCertificateRegistration {
            get {
                return ResourceManager.GetString("AttachCertificateRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee Email.
        /// </summary>
        public static string AttendeeEmail {
            get {
                return ResourceManager.GetString("AttendeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee Mobile.
        /// </summary>
        public static string AttendeeMobile {
            get {
                return ResourceManager.GetString("AttendeeMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee Name.
        /// </summary>
        public static string AttendeeName {
            get {
                return ResourceManager.GetString("AttendeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee Position.
        /// </summary>
        public static string AttendeePosition {
            get {
                return ResourceManager.GetString("AttendeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misuse(block).
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Data.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start with the basic information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there a board of Directors?.
        /// </summary>
        public static string BoardOfDirectors {
            get {
                return ResourceManager.GetString("BoardOfDirectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Your Profile.
        /// </summary>
        public static string BuildYourProfile {
            get {
                return ResourceManager.GetString("BuildYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Sector Non-Profit.
        /// </summary>
        public static string ClassificationSectorNonProfit {
            get {
                return ResourceManager.GetString("ClassificationSectorNonProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        public static string Consultant {
            get {
                return ResourceManager.GetString("Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief history of the
        ///Corporation/Association.
        /// </summary>
        public static string CorperationHistory {
            get {
                return ResourceManager.GetString("CorperationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Name.
        /// </summary>
        public static string CorporateName {
            get {
                return ResourceManager.GetString("CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Profile.
        /// </summary>
        public static string CorporateProfile {
            get {
                return ResourceManager.GetString("CorporateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation  Registration Number.
        /// </summary>
        public static string CorporationRegistrationNumber {
            get {
                return ResourceManager.GetString("CorporationRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Election.
        /// </summary>
        public static string DateElection {
            get {
                return ResourceManager.GetString("DateElection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Of The Project In Days.
        /// </summary>
        public static string DurationOfTheProjectInDays {
            get {
                return ResourceManager.GetString("DurationOfTheProjectInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded Year.
        /// </summary>
        public static string FoundedYear {
            get {
                return ResourceManager.GetString("FoundedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Type on the Organization.
        /// </summary>
        public static string GenderTypeOnTheOrganization {
            get {
                return ResourceManager.GetString("GenderTypeOnTheOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information will let us know more about you.
        /// </summary>
        public static string InformationToBeKnowed {
            get {
                return ResourceManager.GetString("InformationToBeKnowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Account.
        /// </summary>
        public static string InstagramAccount {
            get {
                return ResourceManager.GetString("InstagramAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Public.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Time To Apply.
        /// </summary>
        public static string LastTimeToApply {
            get {
                return ResourceManager.GetString("LastTimeToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Data.
        /// </summary>
        public static string MissingData {
            get {
                return ResourceManager.GetString("MissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Administrator Corporation.
        /// </summary>
        public static string NameOfAdministratorCorporation {
            get {
                return ResourceManager.GetString("NameOfAdministratorCorporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Specialization.
        /// </summary>
        public static string Nospecialization {
            get {
                return ResourceManager.GetString("Nospecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficial Email.
        /// </summary>
        public static string OficialEmail {
            get {
                return ResourceManager.GetString("OficialEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POBox.
        /// </summary>
        public static string POBox {
            get {
                return ResourceManager.GetString("POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private grant and this is your target segment..
        /// </summary>
        public static string PrivateMessage {
            get {
                return ResourceManager.GetString("PrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Type.
        /// </summary>
        public static string ProgramType {
            get {
                return ResourceManager.GetString("ProgramType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public grant and the segment you are targeting is all portal users..
        /// </summary>
        public static string PublicMessage {
            get {
                return ResourceManager.GetString("PublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason to reject.
        /// </summary>
        public static string ReasonToReject {
            get {
                return ResourceManager.GetString("ReasonToReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Data.
        /// </summary>
        public static string RegistrationData {
            get {
                return ResourceManager.GetString("RegistrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Consultant.
        /// </summary>
        public static string SelectConsultant {
            get {
                return ResourceManager.GetString("SelectConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Governorate.
        /// </summary>
        public static string SelectGovernorate {
            get {
                return ResourceManager.GetString("SelectGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Neighborhoods.
        /// </summary>
        public static string SelectNeighborhoods {
            get {
                return ResourceManager.GetString("SelectNeighborhoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Program.
        /// </summary>
        public static string SelectProgram {
            get {
                return ResourceManager.GetString("SelectProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Region.
        /// </summary>
        public static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapchat Account.
        /// </summary>
        public static string SnapchatAccount {
            get {
                return ResourceManager.GetString("SnapchatAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Headquarters.
        /// </summary>
        public static string TrainingHeadquarters {
            get {
                return ResourceManager.GetString("TrainingHeadquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Account.
        /// </summary>
        public static string TwitterAccount {
            get {
                return ResourceManager.GetString("TwitterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Uploade Corporate Photo.
        /// </summary>
        public static string UploadCorpratePhoto {
            get {
                return ResourceManager.GetString("UploadCorpratePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why would you like to join us?.
        /// </summary>
        public static string WhyWouldYouLikeToJoinUs {
            get {
                return ResourceManager.GetString("WhyWouldYouLikeToJoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Details.
        /// </summary>
        public static string WorkshopDetails {
            get {
                return ResourceManager.GetString("WorkshopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Model.
        /// </summary>
        public static string WorkshopModel {
            get {
                return ResourceManager.GetString("WorkshopModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Name.
        /// </summary>
        public static string WorkshopName {
            get {
                return ResourceManager.GetString("WorkshopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Status.
        /// </summary>
        public static string WorkshopStatus {
            get {
                return ResourceManager.GetString("WorkshopStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Account.
        /// </summary>
        public static string YouTubeAccount {
            get {
                return ResourceManager.GetString("YouTubeAccount", resourceCulture);
            }
        }
    }
}
