//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaPeople.KingKhaledFoundation.Admin.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CorporationContactReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorporationContactReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfaPeople.KingKhaledFoundation.Admin.Web.App_GlobalResources.CorporationContactR" +
                            "eport", typeof(CorporationContactReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string Corporate {
            get {
                return ResourceManager.GetString("Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Administrator.
        /// </summary>
        public static string CorporateAdministrator {
            get {
                return ResourceManager.GetString("CorporateAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Administrator Email.
        /// </summary>
        public static string CorporateAdministratorEmail {
            get {
                return ResourceManager.GetString("CorporateAdministratorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation Manager Mobile Number.
        /// </summary>
        public static string CorporationManagerMobile {
            get {
                return ResourceManager.GetString("CorporationManagerMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type.
        /// </summary>
        public static string ModelType {
            get {
                return ResourceManager.GetString("ModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager Email.
        /// </summary>
        public static string ProjectManagerEmail {
            get {
                return ResourceManager.GetString("ProjectManagerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager Mobile Number.
        /// </summary>
        public static string ProjectManagerMobileNumber {
            get {
                return ResourceManager.GetString("ProjectManagerMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Contact Report.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
