//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaPeople.KingKhaledFoundation.Admin.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IncubationRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IncubationRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfaPeople.KingKhaledFoundation.Admin.Web.App_GlobalResources.IncubationRequest", typeof(IncubationRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdvertisingDetails {
            get {
                return ResourceManager.GetString("AdvertisingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdvertisingName {
            get {
                return ResourceManager.GetString("AdvertisingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AllEmployeeNumbers {
            get {
                return ResourceManager.GetString("AllEmployeeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Alms {
            get {
                return ResourceManager.GetString("Alms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AttachAccountantNotes {
            get {
                return ResourceManager.GetString("AttachAccountantNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Baseline {
            get {
                return ResourceManager.GetString("Baseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BoarderMemmbersMeetings {
            get {
                return ResourceManager.GetString("BoarderMemmbersMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BoardMemmbersRoles {
            get {
                return ResourceManager.GetString("BoardMemmbersRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BoardMemmbersRolesForOrganiziation {
            get {
                return ResourceManager.GetString("BoardMemmbersRolesForOrganiziation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BoardOfDirectors {
            get {
                return ResourceManager.GetString("BoardOfDirectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BudgetOfCorprateCommunication {
            get {
                return ResourceManager.GetString("BudgetOfCorprateCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CharteredAccountantNotes {
            get {
                return ResourceManager.GetString("CharteredAccountantNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CommunicationPlan {
            get {
                return ResourceManager.GetString("CommunicationPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConnectionAndPublicRelations {
            get {
                return ResourceManager.GetString("ConnectionAndPublicRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DateOfBoardApproval {
            get {
                return ResourceManager.GetString("DateOfBoardApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DoesTheOrganizationHaveAnAnnualOperatingPlan {
            get {
                return ResourceManager.GetString("DoesTheOrganizationHaveAnAnnualOperatingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DoesTheOrganztionHaveAnStratgicObject {
            get {
                return ResourceManager.GetString("DoesTheOrganztionHaveAnStratgicObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DonorFoundations {
            get {
                return ResourceManager.GetString("DonorFoundations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EntryRequirements {
            get {
                return ResourceManager.GetString("EntryRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FinanceResource {
            get {
                return ResourceManager.GetString("FinanceResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FollowupAndEvaluation {
            get {
                return ResourceManager.GetString("FollowupAndEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FollowUpAndEvaluationAttachment {
            get {
                return ResourceManager.GetString("FollowUpAndEvaluationAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FollowUpAndEvaluationImplentation {
            get {
                return ResourceManager.GetString("FollowUpAndEvaluationImplentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FollowUpAndEvaluationProjectsAndPrograms {
            get {
                return ResourceManager.GetString("FollowUpAndEvaluationProjectsAndPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FullTimeStaff {
            get {
                return ResourceManager.GetString("FullTimeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GovernmentAgencies {
            get {
                return ResourceManager.GetString("GovernmentAgencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HaveRelationAndMedia {
            get {
                return ResourceManager.GetString("HaveRelationAndMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HowManyBoardMembers {
            get {
                return ResourceManager.GetString("HowManyBoardMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HowManyEmployees {
            get {
                return ResourceManager.GetString("HowManyEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HowStaffPerformanceIsMonitored {
            get {
                return ResourceManager.GetString("HowStaffPerformanceIsMonitored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HowTheStratgicPlanDeveloped {
            get {
                return ResourceManager.GetString("HowTheStratgicPlanDeveloped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HowToAttractEmployees {
            get {
                return ResourceManager.GetString("HowToAttractEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HROrganizationStructure {
            get {
                return ResourceManager.GetString("HROrganizationStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HRSpecializedDepartment {
            get {
                return ResourceManager.GetString("HRSpecializedDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HumanResources {
            get {
                return ResourceManager.GetString("HumanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IdentfiyTrainingNeeds {
            get {
                return ResourceManager.GetString("IdentfiyTrainingNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IncubationAdvertisingDetails {
            get {
                return ResourceManager.GetString("IncubationAdvertisingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IncubationAdvertisingModels {
            get {
                return ResourceManager.GetString("IncubationAdvertisingModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IndicateDevelopmentProjects {
            get {
                return ResourceManager.GetString("IndicateDevelopmentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Individuals {
            get {
                return ResourceManager.GetString("Individuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Investments {
            get {
                return ResourceManager.GetString("Investments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsThereIsSpecializeDepartmentForFinancialResources {
            get {
                return ResourceManager.GetString("IsThereIsSpecializeDepartmentForFinancialResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NumberOfDonors {
            get {
                return ResourceManager.GetString("NumberOfDonors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NumberOfFinanceSupporter {
            get {
                return ResourceManager.GetString("NumberOfFinanceSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationEstablishedFor {
            get {
                return ResourceManager.GetString("OrganizationEstablishedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationGovernmentGuid {
            get {
                return ResourceManager.GetString("OrganizationGovernmentGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string organizationStratgicObjectvies {
            get {
                return ResourceManager.GetString("organizationStratgicObjectvies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string organizationStratgicObjectviesAndImplements {
            get {
                return ResourceManager.GetString("organizationStratgicObjectviesAndImplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganzationBudget {
            get {
                return ResourceManager.GetString("OrganzationBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartTimeStaff {
            get {
                return ResourceManager.GetString("PartTimeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PleaseAttachAGovernmentGuide {
            get {
                return ResourceManager.GetString("PleaseAttachAGovernmentGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PleaseAttachTheStrategicPlan {
            get {
                return ResourceManager.GetString("PleaseAttachTheStrategicPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PleaseAttachThisYearOperatingPlan {
            get {
                return ResourceManager.GetString("PleaseAttachThisYearOperatingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PleaseClarify {
            get {
                return ResourceManager.GetString("PleaseClarify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PleaseIndicateNumberDonors {
            get {
                return ResourceManager.GetString("PleaseIndicateNumberDonors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrivateSector {
            get {
                return ResourceManager.GetString("PrivateSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProgramsAndProjects {
            get {
                return ResourceManager.GetString("ProgramsAndProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProjectAllocatedBudget {
            get {
                return ResourceManager.GetString("ProjectAllocatedBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProjectAllocatedBudgetAmount {
            get {
                return ResourceManager.GetString("ProjectAllocatedBudgetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProjectProposal {
            get {
                return ResourceManager.GetString("ProjectProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RequesterName {
            get {
                return ResourceManager.GetString("RequesterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SeparateBudgetOfCorprateCommunication {
            get {
                return ResourceManager.GetString("SeparateBudgetOfCorprateCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SpecializedForEvalutionAndMonitoring {
            get {
                return ResourceManager.GetString("SpecializedForEvalutionAndMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SpecializedForProgramsAndProjects {
            get {
                return ResourceManager.GetString("SpecializedForProgramsAndProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SpecializedInRelationAndMedia {
            get {
                return ResourceManager.GetString("SpecializedInRelationAndMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TheStrategy {
            get {
                return ResourceManager.GetString("TheStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VolumeOfOrganizationRevenue {
            get {
                return ResourceManager.GetString("VolumeOfOrganizationRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VolunteerStaff {
            get {
                return ResourceManager.GetString("VolunteerStaff", resourceCulture);
            }
        }
    }
}
