//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaPeople.KingKhaledFoundation.Admin.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Workshop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Workshop() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfaPeople.KingKhaledFoundation.Admin.Web.App_GlobalResources.Workshop", typeof(Workshop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apologise.
        /// </summary>
        public static string absent {
            get {
                return ResourceManager.GetString("absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Director&apos;s Email.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        public static string Attend {
            get {
                return ResourceManager.GetString("Attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant&apos;s Email.
        /// </summary>
        public static string AttendeeEmail {
            get {
                return ResourceManager.GetString("AttendeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant&apos;s mobile Number.
        /// </summary>
        public static string AttendeeMobile {
            get {
                return ResourceManager.GetString("AttendeeMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant&apos;s Name.
        /// </summary>
        public static string AttendeeName {
            get {
                return ResourceManager.GetString("AttendeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant&apos;s Position.
        /// </summary>
        public static string AttendeePosition {
            get {
                return ResourceManager.GetString("AttendeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Data.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When was the board elected?.
        /// </summary>
        public static string BoardOfDirectors {
            get {
                return ResourceManager.GetString("BoardOfDirectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Classification.
        /// </summary>
        public static string ClassificationSectorNonProfit {
            get {
                return ResourceManager.GetString("ClassificationSectorNonProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting Firm.
        /// </summary>
        public static string Consultant {
            get {
                return ResourceManager.GetString("Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief Introduction about the organization.
        /// </summary>
        public static string CorperationHistory {
            get {
                return ResourceManager.GetString("CorperationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization&apos;s Name.
        /// </summary>
        public static string CorporateName {
            get {
                return ResourceManager.GetString("CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization&apos;s Profile.
        /// </summary>
        public static string CorporateProfile {
            get {
                return ResourceManager.GetString("CorporateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization&apos;s Registration Number.
        /// </summary>
        public static string CorporationRegistrationNumber {
            get {
                return ResourceManager.GetString("CorporationRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Board Election.
        /// </summary>
        public static string DateElection {
            get {
                return ResourceManager.GetString("DateElection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Duration.
        /// </summary>
        public static string DurationOfTheProjectInDays {
            get {
                return ResourceManager.GetString("DurationOfTheProjectInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Qualification and Specialization.
        /// </summary>
        public static string EducationalQualificationAndSpecialization {
            get {
                return ResourceManager.GetString("EducationalQualificationAndSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Establishment.
        /// </summary>
        public static string FoundedYear {
            get {
                return ResourceManager.GetString("FoundedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Account.
        /// </summary>
        public static string InstagramAccount {
            get {
                return ResourceManager.GetString("InstagramAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Public.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string LastTimeToApply {
            get {
                return ResourceManager.GetString("LastTimeToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Organization&apos;s CEO.
        /// </summary>
        public static string NameOfAdministratorCorporation {
            get {
                return ResourceManager.GetString("NameOfAdministratorCorporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Email.
        /// </summary>
        public static string OficialEmail {
            get {
                return ResourceManager.GetString("OficialEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POBox.
        /// </summary>
        public static string POBox {
            get {
                return ResourceManager.GetString("POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Tasks.
        /// </summary>
        public static string PositionTasks {
            get {
                return ResourceManager.GetString("PositionTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private advertisement for specific targeted NPOs.
        /// </summary>
        public static string PrivateMessage {
            get {
                return ResourceManager.GetString("PrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Type.
        /// </summary>
        public static string ProgramType {
            get {
                return ResourceManager.GetString("ProgramType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is open advertisement for all NPOs.
        /// </summary>
        public static string PublicMessage {
            get {
                return ResourceManager.GetString("PublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationData {
            get {
                return ResourceManager.GetString("RegistrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Consulting Firm.
        /// </summary>
        public static string SelectConsultant {
            get {
                return ResourceManager.GetString("SelectConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Governorate.
        /// </summary>
        public static string SelectGovernorate {
            get {
                return ResourceManager.GetString("SelectGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Workshop Topic.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Neighborhoods.
        /// </summary>
        public static string SelectNeighborhoods {
            get {
                return ResourceManager.GetString("SelectNeighborhoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Region.
        /// </summary>
        public static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapchat Account.
        /// </summary>
        public static string SnapchatAccount {
            get {
                return ResourceManager.GetString("SnapchatAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number if any.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Venue.
        /// </summary>
        public static string TrainingHeadquarters {
            get {
                return ResourceManager.GetString("TrainingHeadquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Account.
        /// </summary>
        public static string TwitterAccount {
            get {
                return ResourceManager.GetString("TwitterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why would you like to join us?.
        /// </summary>
        public static string WhyWouldYouLikeToJoinUs {
            get {
                return ResourceManager.GetString("WhyWouldYouLikeToJoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Details.
        /// </summary>
        public static string WorkshopDetails {
            get {
                return ResourceManager.GetString("WorkshopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Invitations.
        /// </summary>
        public static string WorkshopInvitations {
            get {
                return ResourceManager.GetString("WorkshopInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Topic.
        /// </summary>
        public static string WorkshopModel {
            get {
                return ResourceManager.GetString("WorkshopModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Name.
        /// </summary>
        public static string WorkshopName {
            get {
                return ResourceManager.GetString("WorkshopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Evaluation Report.
        /// </summary>
        public static string WorkshopRatingReport {
            get {
                return ResourceManager.GetString("WorkshopRatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Status.
        /// </summary>
        public static string WorkshopStatus {
            get {
                return ResourceManager.GetString("WorkshopStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Account.
        /// </summary>
        public static string YouTubeAccount {
            get {
                return ResourceManager.GetString("YouTubeAccount", resourceCulture);
            }
        }
    }
}
