//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaPeople.KingKhalidFoundation.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Grant {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Grant() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfaPeople.KingKhalidFoundation.Web.App_GlobalResources.Grant", typeof(Grant).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Source.
        /// </summary>
        public static string FundingSource {
            get {
                return ResourceManager.GetString("FundingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Details.
        /// </summary>
        public static string GrantDetails {
            get {
                return ResourceManager.GetString("GrantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Join.
        /// </summary>
        public static string GrantJoin {
            get {
                return ResourceManager.GetString("GrantJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Name.
        /// </summary>
        public static string GrantName {
            get {
                return ResourceManager.GetString("GrantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines for Grant.
        /// </summary>
        public static string GuidelinesForGrant {
            get {
                return ResourceManager.GetString("GuidelinesForGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is public.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Deadline.
        /// </summary>
        public static string LastTimeToApply {
            get {
                return ResourceManager.GetString("LastTimeToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Proposal Deadline.
        /// </summary>
        public static string MaximumDateForIntroductionOfProjectProposal {
            get {
                return ResourceManager.GetString("MaximumDateForIntroductionOfProjectProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline for work plan and Budget Submission.
        /// </summary>
        public static string MaximumDateForWorkPlanAndBudget {
            get {
                return ResourceManager.GetString("MaximumDateForWorkPlanAndBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Type.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Proposal.
        /// </summary>
        public static string ProjectProposal {
            get {
                return ResourceManager.GetString("ProjectProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Grant Funding Source.
        /// </summary>
        public static string SelectGrantFundingSource {
            get {
                return ResourceManager.GetString("SelectGrantFundingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Grant Type.
        /// </summary>
        public static string SelectGrantModel {
            get {
                return ResourceManager.GetString("SelectGrantModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Intervention.
        /// </summary>
        public static string SelectGrantTypeOfIntervention {
            get {
                return ResourceManager.GetString("SelectGrantTypeOfIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Officer.
        /// </summary>
        public static string SelectSpecialist {
            get {
                return ResourceManager.GetString("SelectSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Officer.
        /// </summary>
        public static string SpecialistForTheGrant {
            get {
                return ResourceManager.GetString("SpecialistForTheGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private grant and this is your target segment..
        /// </summary>
        public static string ThisIsAPrivateGrantAndThisIsYourTargetSegment {
            get {
                return ResourceManager.GetString("ThisIsAPrivateGrantAndThisIsYourTargetSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public grant and the segment you are targeting is all portal users..
        /// </summary>
        public static string ThisIsAPublicGrantAndTheSegmentYouAreTargetingIsAllPortalUsers {
            get {
                return ResourceManager.GetString("ThisIsAPublicGrantAndTheSegmentYouAreTargetingIsAllPortalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
