//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaPeople.KingKhalidFoundation.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GrantWorkshops {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrantWorkshops() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfaPeople.KingKhalidFoundation.Web.App_GlobalResources.GrantWorkshops", typeof(GrantWorkshops).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apologise.
        /// </summary>
        public static string absent {
            get {
                return ResourceManager.GetString("absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To attach the nominations&apos; data, please click here.
        /// </summary>
        public static string AddAttendee {
            get {
                return ResourceManager.GetString("AddAttendee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        public static string Attend {
            get {
                return ResourceManager.GetString("Attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Organizations.
        /// </summary>
        public static string AttendedUsers {
            get {
                return ResourceManager.GetString("AttendedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Details.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Duration.
        /// </summary>
        public static string DurationOfTheProjectInDays {
            get {
                return ResourceManager.GetString("DurationOfTheProjectInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Name.
        /// </summary>
        public static string GrantName {
            get {
                return ResourceManager.GetString("GrantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Workshop.
        /// </summary>
        public static string GrantWorkshop {
            get {
                return ResourceManager.GetString("GrantWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Workshop Details.
        /// </summary>
        public static string GrantWorkshopDetails {
            get {
                return ResourceManager.GetString("GrantWorkshopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Status.
        /// </summary>
        public static string InvitationStatus {
            get {
                return ResourceManager.GetString("InvitationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Public.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join To The Workshop.
        /// </summary>
        public static string JoinToTheWorkshop {
            get {
                return ResourceManager.GetString("JoinToTheWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Deadline.
        /// </summary>
        public static string LastTimeToApply {
            get {
                return ResourceManager.GetString("LastTimeToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Date to join to workshop.
        /// </summary>
        public static string MaximumDateToJoinToWorkshop {
            get {
                return ResourceManager.GetString("MaximumDateToJoinToWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private grant and this is your target segment..
        /// </summary>
        public static string PrivateMessage {
            get {
                return ResourceManager.GetString("PrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public grant and the segment you are targeting is all portal users..
        /// </summary>
        public static string PublicMessage {
            get {
                return ResourceManager.GetString("PublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Organizations.
        /// </summary>
        public static string SegmentTargetedUsers {
            get {
                return ResourceManager.GetString("SegmentTargetedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Consultant.
        /// </summary>
        public static string SelectConsultant {
            get {
                return ResourceManager.GetString("SelectConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Governorate.
        /// </summary>
        public static string SelectGovernorate {
            get {
                return ResourceManager.GetString("SelectGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Grant.
        /// </summary>
        public static string SelectGrant {
            get {
                return ResourceManager.GetString("SelectGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Grant Type.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Neighborhoods.
        /// </summary>
        public static string SelectNeighborhoods {
            get {
                return ResourceManager.GetString("SelectNeighborhoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Region.
        /// </summary>
        public static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private grant and this is your target segment..
        /// </summary>
        public static string ThisIsAPrivateGrantAndThisIsYourTargetSegment {
            get {
                return ResourceManager.GetString("ThisIsAPrivateGrantAndThisIsYourTargetSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public grant and the segment you are targeting is all portal users..
        /// </summary>
        public static string ThisIsAPublicGrantAndTheSegmentYouAreTargetingIsAllPortalUsers {
            get {
                return ResourceManager.GetString("ThisIsAPublicGrantAndTheSegmentYouAreTargetingIsAllPortalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workshop  Venue.
        /// </summary>
        public static string TrainingHeadquarters {
            get {
                return ResourceManager.GetString("TrainingHeadquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Details.
        /// </summary>
        public static string WorkshopDetails {
            get {
                return ResourceManager.GetString("WorkshopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Model.
        /// </summary>
        public static string WorkshopModel {
            get {
                return ResourceManager.GetString("WorkshopModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workshop Title.
        /// </summary>
        public static string WorkshopName {
            get {
                return ResourceManager.GetString("WorkshopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Status.
        /// </summary>
        public static string WorkshopStatus {
            get {
                return ResourceManager.GetString("WorkshopStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Type.
        /// </summary>
        public static string WorkshopType {
            get {
                return ResourceManager.GetString("WorkshopType", resourceCulture);
            }
        }
    }
}
