//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaPeople.KingKhalidFoundation.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GrantProjectIdeaRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrantProjectIdeaRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfaPeople.KingKhalidFoundation.Web.App_GlobalResources.GrantProjectIdeaRequest", typeof(GrantProjectIdeaRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age From.
        /// </summary>
        public static string AgeFrom {
            get {
                return ResourceManager.GetString("AgeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age To.
        /// </summary>
        public static string AgeTo {
            get {
                return ResourceManager.GetString("AgeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string CorporateName {
            get {
                return ResourceManager.GetString("CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Profile.
        /// </summary>
        public static string CorporateProfile {
            get {
                return ResourceManager.GetString("CorporateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Beneficiaries.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Of The Project In Months.
        /// </summary>
        public static string DurationOfTheProjectInMonths {
            get {
                return ResourceManager.GetString("DurationOfTheProjectInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the experience of the organization in addressing problems.
        /// </summary>
        public static string ExperienceOfTheOrganization {
            get {
                return ResourceManager.GetString("ExperienceOfTheOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string Feadback {
            get {
                return ResourceManager.GetString("Feadback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate.
        /// </summary>
        public static string Governorate {
            get {
                return ResourceManager.GetString("Governorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download fill out and attach the project proposal forms attached above.
        /// </summary>
        public static string GPP_Attachments {
            get {
                return ResourceManager.GetString("GPP_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Name.
        /// </summary>
        public static string GrantName {
            get {
                return ResourceManager.GetString("GrantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines For Grant.
        /// </summary>
        public static string GuidelinesForGrant {
            get {
                return ResourceManager.GetString("GuidelinesForGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention: How will the Problem be Solved and what are the expected Outcomes?.
        /// </summary>
        public static string Intervention {
            get {
                return ResourceManager.GetString("Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Project Idea.
        /// </summary>
        public static string PEY_ProjectIdea {
            get {
                return ResourceManager.GetString("PEY_ProjectIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the problem that needs to be resolved? Support this with Statistics or Research.
        /// </summary>
        public static string problemToBeSolved {
            get {
                return ResourceManager.GetString("problemToBeSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Idea.
        /// </summary>
        public static string ProjectIdea {
            get {
                return ResourceManager.GetString("ProjectIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Partners.
        /// </summary>
        public static string ProjectPartners {
            get {
                return ResourceManager.GetString("ProjectPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project Title.
        /// </summary>
        public static string ProjectProposalName {
            get {
                return ResourceManager.GetString("ProjectProposalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where will the Project be implemented?.
        /// </summary>
        public static string ProjectsImplmented {
            get {
                return ResourceManager.GetString("ProjectsImplmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectTargetSegmant.
        /// </summary>
        public static string SelectTargetSegmant {
            get {
                return ResourceManager.GetString("SelectTargetSegmant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your project idea that aligns with the grant Guidelines ?.
        /// </summary>
        public static string WhartIsYourProjectIdea {
            get {
                return ResourceManager.GetString("WhartIsYourProjectIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the plan to ensure the continuity and growth of the project(Sustainability).
        /// </summary>
        public static string WhatIsThePlanToEnsureTheContinuityAndGrowthOfTherPojectSustainability {
            get {
                return ResourceManager.GetString("WhatIsThePlanToEnsureTheContinuityAndGrowthOfTherPojectSustainability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Targeted Beneficiaries.
        /// </summary>
        public static string WhatIsTheTargetSegment {
            get {
                return ResourceManager.GetString("WhatIsTheTargetSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where The Project Will Be Implemented ?.
        /// </summary>
        public static string WhereTheProjectsWillBeImplemented {
            get {
                return ResourceManager.GetString("WhereTheProjectsWillBeImplemented", resourceCulture);
            }
        }
    }
}
