//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaPeople.KingKhalidFoundation.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IncubationWorkshopRating {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IncubationWorkshopRating() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfaPeople.KingKhalidFoundation.Web.App_GlobalResources.IncubationWorkshopRating", typeof(IncubationWorkshopRating).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate the Trainer’s ability in achieving the workshop goals.
        /// </summary>
        public static string AbilityToAchieveAGoal {
            get {
                return ResourceManager.GetString("AbilityToAchieveAGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability To Manage Discussion And Handle Questions.
        /// </summary>
        public static string AbilityToManageDiscussionAndHandleQuestions {
            get {
                return ResourceManager.GetString("AbilityToManageDiscussionAndHandleQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Language.
        /// </summary>
        public static string BodyLanguage {
            get {
                return ResourceManager.GetString("BodyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarity Of Voice.
        /// </summary>
        public static string ClarityOfVoiceAndTone {
            get {
                return ResourceManager.GetString("ClarityOfVoiceAndTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is there is any commentes on the trainer? (if yes write it).
        /// </summary>
        public static string CommentsAboutTheTrainer {
            get {
                return ResourceManager.GetString("CommentsAboutTheTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corprate Name.
        /// </summary>
        public static string CorprateName {
            get {
                return ResourceManager.GetString("CorprateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate The Trainer.
        /// </summary>
        public static string EvaluateTheTrainer {
            get {
                return ResourceManager.GetString("EvaluateTheTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you evaluate the workshop?.
        /// </summary>
        public static string EvaluateTheWorkshop {
            get {
                return ResourceManager.GetString("EvaluateTheWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to evaluate the training material?.
        /// </summary>
        public static string EvaluateTrainingMaterial {
            get {
                return ResourceManager.GetString("EvaluateTrainingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Date.
        /// </summary>
        public static string EvaluationDate {
            get {
                return ResourceManager.GetString("EvaluationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catering.
        /// </summary>
        public static string Hosting {
            get {
                return ResourceManager.GetString("Hosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Do You Evaluate Particpation ?.
        /// </summary>
        public static string HowDoYouEvaluateParticpation {
            get {
                return ResourceManager.GetString("HowDoYouEvaluateParticpation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you evaluate the workshop?.
        /// </summary>
        public static string HowDoYouEvaluateTheWorkshop {
            get {
                return ResourceManager.GetString("HowDoYouEvaluateTheWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what extent will the workshop be useful?.
        /// </summary>
        public static string IsWorkshopUseful {
            get {
                return ResourceManager.GetString("IsWorkshopUseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking The Training Material To Reality.
        /// </summary>
        public static string LinkingTheTrainingMaterialToReality {
            get {
                return ResourceManager.GetString("LinkingTheTrainingMaterialToReality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastery Of Training Material.
        /// </summary>
        public static string MasteryOfTrainingMaterial {
            get {
                return ResourceManager.GetString("MasteryOfTrainingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasone if the answer is Did Not Achieve Goals?.
        /// </summary>
        public static string ReasoneAchieveGoals {
            get {
                return ResourceManager.GetString("ReasoneAchieveGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason if the answer is bad?.
        /// </summary>
        public static string ReasonForBadAnswer {
            get {
                return ResourceManager.GetString("ReasonForBadAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason if the answer is unfit?.
        /// </summary>
        public static string ReasonForUnfit {
            get {
                return ResourceManager.GetString("ReasonForUnfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason if the answer is Unuseful?.
        /// </summary>
        public static string ReasonForUnuseful {
            get {
                return ResourceManager.GetString("ReasonForUnuseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester Name.
        /// </summary>
        public static string RequesterName {
            get {
                return ResourceManager.GetString("RequesterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        public static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Points of strength and weakness the workshop?.
        /// </summary>
        public static string StrenghtAndWeaknessPoints {
            get {
                return ResourceManager.GetString("StrenghtAndWeaknessPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength Point.
        /// </summary>
        public static string StrengthPoint {
            get {
                return ResourceManager.GetString("StrengthPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ability To Deliver The Information.
        /// </summary>
        public static string TheAbilityToDeliverTheInformation {
            get {
                return ResourceManager.GetString("TheAbilityToDeliverTheInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to evaluate the training material?.
        /// </summary>
        public static string TrainingMaterial {
            get {
                return ResourceManager.GetString("TrainingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weakness Point.
        /// </summary>
        public static string WeaknessPoint {
            get {
                return ResourceManager.GetString("WeaknessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what extent does the workshop achieve the objectives?.
        /// </summary>
        public static string WorkshopAchieveObjectives {
            get {
                return ResourceManager.GetString("WorkshopAchieveObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workshop venue.
        /// </summary>
        public static string WorkshopClass {
            get {
                return ResourceManager.GetString("WorkshopClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Rating.
        /// </summary>
        public static string WorkshopRating {
            get {
                return ResourceManager.GetString("WorkshopRating", resourceCulture);
            }
        }
    }
}
